import type { FeedItem } from "./FeedCard";
import feedKisschase from "@/assets/feed-kisschase.jpg";
import feedPrompt from "@/assets/feed-prompt.jpg";
import feedDatenight from "@/assets/feed-datenight.jpg";
import feedTravel from "@/assets/feed-travel.jpg";
import feedMilestone from "@/assets/feed-milestone.jpg";
import feedJournal from "@/assets/feed-journal.jpg";

export const sampleFeedData: FeedItem[] = [
  {
    id: "0",
    type: "update",
    tag: "🔥 Kiss Chase",
    tagColor: "text-us-coral",
    title: "Challenge your partner to Kiss Chase!",
    subtitle: "A real-world game of chase with rewards",
    body: "Turn on location, set a time limit, pick a reward — then go find your partner!",
    image: feedKisschase,
    timeAgo: "New",
    link: "/kiss-chase",
  },
  {
    id: "1",
    type: "prompt",
    tag: "Daily Prompt",
    tagColor: "text-us-coral",
    title: "What made you smile today?",
    subtitle: "Take a moment to share something positive",
    body: "Sharing small joys strengthens your bond. Tap to answer today's connection prompt and see what your partner said.",
    image: feedPrompt,
    timeAgo: "Just now",
    liked: false,
  },
  {
    id: "2",
    type: "quiz",
    tag: "Quiz · Love Maps",
    tagColor: "text-us-gold",
    title: "How well do you know their favourites?",
    body: "A new 5-question quiz is ready. Answer before your partner to trigger the 'Blind Reveal' moment. Your streak: 12 days 🔥",
    image: feedDatenight,
    timeAgo: "2h ago",
    liked: true,
  },
  {
    id: "3",
    type: "reminder",
    tag: "Reminder · Admin",
    tagColor: "text-us-navy",
    title: "Car insurance renewal in 5 days",
    subtitle: "Policy #AX-2847 · Admiral",
    body: "Your joint car insurance expires on Feb 18. Documents are saved in your Life Database under 'Insurance'.",
    timeAgo: "4h ago",
  },
  {
    id: "4",
    type: "milestone",
    tag: "Milestone",
    tagColor: "text-us-sage",
    title: "🎉 3 months of daily check-ins!",
    body: "You and your partner have completed 90 consecutive daily prompts. Research shows consistent emotional check-ins improve relationship satisfaction by 34%.",
    image: feedMilestone,
    timeAgo: "Today",
    liked: true,
    saved: true,
  },
  {
    id: "5",
    type: "blog",
    tag: "Read · Relationships",
    tagColor: "text-muted-foreground",
    title: "The 5-minute ritual that transformed our mornings",
    subtitle: "From the US Journal",
    body: "Couples who share a brief morning ritual report feeling 40% more connected throughout the day. Here's a simple framework to try this week.",
    image: feedJournal,
    timeAgo: "6h ago",
  },
  {
    id: "6",
    type: "update",
    tag: "Partner Update",
    tagColor: "text-us-terracotta",
    title: "Woody completed 3 tasks today ✓",
    body: "Grocery shopping, booked dentist appointment, and updated the emergency contacts list. Send a thank you note?",
    timeAgo: "1h ago",
  },
  {
    id: "7",
    type: "prompt",
    tag: "Gratitude",
    tagColor: "text-us-coral",
    title: "3 things I appreciate about you…",
    body: "Your partner left you a gratitude note this morning. Tap to read it — it'll be revealed with a little surprise ✨",
    image: feedTravel,
    timeAgo: "8h ago",
    liked: true,
  },
];
